---
- name: Install preliminary dependencies
  apt: name={{ item }}
       state=present
  with_items:
  - apt-transport-https # for additional repositories

# setup Aufs
- name: Install extra kernel modules for aufs
  apt: "pkg=linux-image-extra-{{ansible_kernel}} state=present"

- name: Enable aufs kernel module
  modprobe: name=aufs state=present

# otherwise sshcommand creates the user,
# giving us no control
# user is automatically added to docker and dokku groups
# by postinst script
- name: Create dokku user
  user: >
    name=dokku home="{{dokku_root}}" system=yes

- name: Add Docker repository key
  apt_key: >
    id="{{docker_repo_key}}" state=present keyserver="keyserver.ubuntu.com"

- name: Add Docker repository
  apt_repository: >
    repo="{{docker_repo_url}}" state=present

- name: Add dokku repository key
  apt_key: >
    id="{{dokku_repo_key}}" state=present keyserver=keys.gnupg.net

- name: Add dokku repository
  apt_repository: >
    repo="{{dokku_repo_url}}" state=present

- name: "Install {{dokku_pkg}}"
  apt: >
    name="{{dokku_pkg}}" state=present update_cache=yes

- name: Setup VHOST file
  copy: >
    dest="{{dokku_root}}/VHOST"
    owner=dokku group=dokku mode=0644
    content="{{dokku_vhost | mandatory}}"
